name: LaTeX compilation
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Merge main branch
        run: |
          git config user.name HoshinoKeisuke
          git config user.email catkekke18635@gmail.com
          git checkout pdf
          git merge main
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file:
            main.tex
      - name: Push PDF file
        run: |
          git add --all
          git commit -m "LaTeX compilation"
          git push --force origin pdf

# In the repository, go Setting/Actions/General/Workflow permissions and set to "read and write perission"
